### ISSUE TITLE
Why this and not "yarn link"?

### ISSUE THREAD

**Issue by gonzalo-lopezlabs** [sashimi36/next-bundle-junoblocks#1]
Hi Sashimi, nice to meet you.
I would like to know why you chose this way instead of doing "yarn link" in junoblocks and "yarn link junoblocks" in the next app.

**Comment by sashimi36** [comment]
Hey @lopezgonzalo89 thanks for reaching out.  We find `yarn link` unstable and this plugin is more or less of a robust solution around it. Hope that answers your question!

**Comment by lopezgonzalo89** [comment]
Thanks, this strategy looks great!

**Comment by gonzalo-lopezlabs** [comment]
Thanks, this strategy looks great!
